# -*- coding: utf-8 -*-
"""ML_Ttitanic_RealDataset.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fuo3IDCkfgtfdOKsgk2PE5nriahsr5IE
"""

import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
df=pd.read_csv('titanic.csv')
df

# Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
#        'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
#       dtype='object')
df.head()
df.columns
df.info()
df.isnull().sum()

surv_gend=df.groupby('Survived')['Sex'].sum()
sns.countplot(data=df,x='Survived',hue='Sex')
plt.show()
sns.countplot(data=df,x='Survived',hue='Pclass')
plt.show()
# corr=df.corr()
# sns.heatmap(corr,annot=True)
plt.hist(df['Age'],bins=5)

df['Age']=df['Age'].fillna(df['Age'].median())
df.isnull().sum()
df['Embarked']=df['Embarked'].fillna(df['Embarked'].mode()[0])
df.isnull().sum()
df.drop('Cabin',axis=1,inplace=True)
df.isnull().sum()
df.drop('PassengerId',axis=1,inplace=True)
df.drop('Name',axis=1,inplace=True)
df.drop('Ticket',axis=1,inplace=True)
df

df=pd.get_dummies(df,columns=['Sex','Embarked'])
df

from sklearn.model_selection import train_test_split
x=df.drop('Survived',axis=1)
y=df['Survived']
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
x_train_scaled=sc.fit_transform(x_train)
x_test_scaled=sc.transform(x_test)

from sklearn.linear_model import LogisticRegression
lr=LogisticRegression()
lr.fit(x_train,y_train)
y_pred1=lr.predict(x_test)
train_Acc = lr.score(x_train, y_train)
print("train acc",train_Acc)
test_acc = lr.score(x_test, y_test)
print("test acc",test_acc)

from sklearn.neighbors import KNeighborsClassifier
knn=KNeighborsClassifier(n_neighbors=5)
knn.fit(x_train,y_train)
y_pred2=knn.predict(x_test)
train_Acc = knn.score(x_train, y_train)
print("train acc",train_Acc)
test_acc = knn.score(x_test, y_test)
print("test acc",test_acc)

from sklearn.tree import DecisionTreeClassifier
dt=DecisionTreeClassifier()
dt.fit(x_train,y_train)
y_pred3=dt.predict(x_test)
train_Acc = dt.score(x_train, y_train)
print("train acc",train_Acc)
test_acc = dt.score(x_test, y_test)
print("test acc",test_acc)

from sklearn.ensemble import RandomForestClassifier
rf=RandomForestClassifier(n_estimators=100)
rf.fit(x_train,y_train)
y_pred4=rf.predict(x_test)
train_Acc = rf.score(x_train, y_train)
print("train acc",train_Acc)
test_acc = rf.score(x_test, y_test)
print("test acc",test_acc)

from sklearn.svm import SVC
model_svm=SVC(kernel='linear',random_state=42)
model_svm.fit(x_train_scaled,y_train)
y_pred5=model_svm.predict(x_test_scaled)
train_Acc = model_svm.score(x_train, y_train)
print("train acc",train_Acc)
test_acc = model_svm.score(x_test, y_test)
print("test acc",test_acc)

from sklearn.metrics import classification_report,accuracy_score
print(classification_report(y_test,y_pred))
print(accuracy_score(y_test,y_pred1))
print(accuracy_score(y_test,y_pred2))
print(accuracy_score(y_test,y_pred3))
print(accuracy_score(y_test,y_pred4))
print(accuracy_score(y_test,y_pred5))

from sklearn.metrics import confusion_matrix


cm = confusion_matrix(y_test, y_pred1)

plt.figure(figsize=(8, 6))
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues',
            xticklabels=['Not Survived', 'Survived'],
            yticklabels=['Not Survived', 'Survived'])
plt.xlabel('Predicted')
plt.ylabel('Actual')
plt.title('Confusion Matrix for Random Forest Model')
plt.show()

cm = confusion_matrix(y_test, y_pred2)

plt.figure(figsize=(8, 6))
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues',
            xticklabels=['Not Survived', 'Survived'],
            yticklabels=['Not Survived', 'Survived'])
plt.xlabel('Predicted')
plt.ylabel('Actual')
plt.title('Confusion Matrix for Random Forest Model')
plt.show()
cm = confusion_matrix(y_test, y_pred3)

plt.figure(figsize=(8, 6))
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues',
            xticklabels=['Not Survived', 'Survived'],
            yticklabels=['Not Survived', 'Survived'])
plt.xlabel('Predicted')
plt.ylabel('Actual')
plt.title('Confusion Matrix for Random Forest Model')
plt.show()
cm = confusion_matrix(y_test, y_pred4)

plt.figure(figsize=(8, 6))
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues',
            xticklabels=['Not Survived', 'Survived'],
            yticklabels=['Not Survived', 'Survived'])
plt.xlabel('Predicted')
plt.ylabel('Actual')
plt.title('Confusion Matrix for Random Forest Model')
plt.show()

cm = confusion_matrix(y_test, y_pred5)

plt.figure(figsize=(8, 6))
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues',
            xticklabels=['Not Survived', 'Survived'],
            yticklabels=['Not Survived', 'Survived'])
plt.xlabel('Predicted')
plt.ylabel('Actual')
plt.title('Confusion Matrix for Random Forest Model')
plt.show()

#model ka ghoal tha ke kon banda survive krta hai aur kon nhi krta matlab target variable survived tha hamne dekhna tha le baki komn konse variable survived se effect hote hyn aur sabse acha jo model tha wo logistci regression tha aur sbse ziada overfitting decision tree ne ki