# -*- coding: utf-8 -*-
"""ML_Task2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vlDoJAzcPVlu18qtrdOmClBDaNip9Zlj
"""

import pandas as pd
import numpy as np
df=pd.read_csv("netflix_ml.csv")
df

df.isnull().sum()
df.shape
df.dtypes
df.info()

df.head(2)

features = [
    "director",
    "country",
    "rating",
    "release_year",
    "listed_in"
]

x=df[features]
y=df['type']

from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()

for col in x.columns:
  if x[col].dtype=="object":
    x[col]=le.fit_transform(x[col])

y = le.fit_transform(y)

from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

from sklearn.tree import DecisionTreeClassifier

dt_model=DecisionTreeClassifier()
dt_model.fit(x_train,y_train)
pred_dt=dt_model.predict(x_test)

from sklearn.metrics import accuracy_score
acc_dt=accuracy_score(y_test,pred_dt)
print("Decision Tree Accuracy Score:",acc_dt)



from sklearn.ensemble import RandomForestClassifier

rf_model=RandomForestClassifier(n_estimators=100,
    random_state=42)
rf_model.fit(x_train,y_train)
rf_pred=rf_model.predict(x_test)

acc_rf=accuracy_score(y_test,rf_pred)
print("Random Forest Accuracy Score:",acc_rf)

from sklearn.linear_model import LogisticRegression


Lr_model=LogisticRegression()
Lr_model.fit(x_train,y_train)
Lr_pred=Lr_model.predict(x_test)

acc_lr=accuracy_score(y_test,Lr_pred)
print("Logistic Regression Accuracy Score:",acc_lr)

from sklearn.neighbors import KNeighborsClassifier
knn_model=KNeighborsClassifier(n_neighbors=5)
knn_model.fit(x_train,y_train)
knn_pred=knn_model.predict(x_test)

acc_knn=accuracy_score(y_test,knn_pred)
print("KNN Accuracy Score:",acc_knn)

results={
    "Decision Tree":acc_dt,
    "Random Forest":acc_rf,
    "Logistic Regression":acc_lr,
    "KNN":acc_knn
}
for model,acc in results.items():
  print(f"{model}:{acc:.4f}")

best_model = rf_model

print("Best Model: Random Forest")

from sklearn.metrics import confusion_matrix

cm = confusion_matrix(y_test, rf_pred)

print(cm)

import pickle
pickle.dumb=(rf_model,open("content_type_model.pkl","wb"))

import matplotlib.pyplot as plt
model=list(results.keys())
acc=list(results.values())
plt.figure(figsize=(8,5))
plt.bar(model,acc)
plt.title("Model Accuracy Comparison")

plt.ylabel("Accuracy")
plt.show()



print(np.unique(y))

print(le.classes_)

from sklearn.metrics import classification_report

target_names = ["Movie", "TV Show"]

print("="*60)
print("LOGISTIC REGRESSION")
print(classification_report(y_test, Lr_pred, target_names=target_names))

print("="*60)
print("DECISION TREE")
print(classification_report(y_test, pred_dt, target_names=target_names))

print("="*60)
print("RANDOM FOREST")
print(classification_report(y_test, rf_pred, target_names=target_names))

print("="*60)
print("KNN")
print(classification_report(y_test, knn_pred, target_names=target_names))

