# -*- coding: utf-8 -*-
"""ML_Task3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1K0dyk7b9hWgHwPoJu3K75kyGVxHgvQwC
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

df=pd.read_csv("netflix_ml.csv")
df

df.isnull().sum()
df.shape

print("unique rating")
print(df['rating'].unique())

print("=========================")

print("Number of Rating Categories:")

print(df['rating'].nunique())

print("=========================")

print("Number of Ratings")

print(df['rating'].value_counts())
df.head(2)

features = [
    "type",
    "director",
    "country",
    "release_year",
    "duration",
    "listed_in"
]

df_model=df[features+['rating']].copy()
df_model

df_model.isnull().sum()

x=df_model.drop("rating",axis=1)
y=df['rating']
x
y

from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
feature_encoders = {}
for pk in x.columns:
  le=LabelEncoder()
  x[pk]=le.fit_transform(x[pk].astype(str))
  feature_encoders[pk] = le

target_encoder = LabelEncoder()

y = target_encoder.fit_transform(y)
y
x

print(target_encoder.classes_)

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score,classification_report,confusion_matrix
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score

x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)
print(x_train.shape)
print(y_train.shape)
print(x_test.shape)
print(y_test.shape)

dt=DecisionTreeClassifier()
dt.fit(x_train,y_train)
dt_pred=dt.predict(x_test)
dt_acc=accuracy_score(y_test,dt_pred)

print("decision tree accuracy",round(dt_acc,4))

from sklearn.ensemble import RandomForestClassifier
rf=RandomForestClassifier(n_estimators=100,max_depth=10,random_state=42)
rf.fit(x_train,y_train)
rf_pred=rf.predict(x_test)
rf_acc=accuracy_score(y_test,rf_pred)

print("random forest accuracy",round(rf_acc,4))

from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

lr = LogisticRegression(max_iter=1000)

lr.fit(x_train, y_train)

lr_pred = lr.predict(x_test)

lr_acc = accuracy_score(y_test, lr_pred)

print("Logistic Regression Accuracy:", round(lr_acc,4))

from sklearn.model_selection import GridSearchCV
param_grid={
    "n_estimators":[100,200],
    "max_depth":[10,20,None],
    "min_samples_split":[2,5,10],
    "min_samples_leaf":[1,2,4]

}

rff=RandomForestClassifier(random_state=42)

grid_search=GridSearchCV(estimator=rff,param_grid=param_grid,cv=5,scoring='accuracy',n_jobs=-1,verbose=1)

grid_search.fit(x_train, y_train)

print("Best Parameters")

from sklearn.neighbors import KNeighborsClassifier

knn = KNeighborsClassifier(n_neighbors=5)

knn.fit(x_train, y_train)

knn_pred = knn.predict(x_test)

knn_acc = accuracy_score(y_test, knn_pred)

print("KNN Accuracy:", round(knn_acc,4))

best_rf = grid_search.best_estimator_
best_rf
best_pred = best_rf.predict(x_test)
from sklearn.metrics import accuracy_score

print("Accuracy:", accuracy_score(y_test, best_pred))

models = ["DT", "RF", "LR", "KNN"]

accuracy = [dt_acc, rf_acc, lr_acc, knn_acc]

plt.plot(models, accuracy, marker='o')
plt.xlabel('Models')
plt.ylabel('Accuracy')
plt.title('Model Accuracy Comparison')

plt.show()

from sklearn.metrics import classification_report

print(classification_report(y_test, best_pred))

from sklearn.metrics import confusion_matrix
cm=confusion_matrix(y_test,best_pred)
cm

"""Feature Importance

"""

imp=pd.DataFrame({'feature':x.columns,'importance':best_rf.feature_importances_})
importance=imp.sort_values(by='importance',ascending=False)
importance

plt.figure(figsize=(5,3))
plt.bar(importance['feature'],importance['importance'])
plt.xticks(rotation=40)
plt.xlabel('Features')
plt.ylabel('Importance')
plt.title("Feature Importance")
plt.show()

import pickle

pickle.dump(best_rf, open("rating_classifier.pkl","wb"))

print("Model Saved Successfully")

df.head()

