# -*- coding: utf-8 -*-
"""ML_Task1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uR8C2lNWnstXiCwgLMdWcNAv3DNjRW29
"""

import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.feature_extraction.text import CountVectorizer
from sklearn.metrics.pairwise import cosine_similarity

df=pd.read_csv("netflix_ml.csv")
df

df.head()

df.dtypes

df.columns

df.isnull().sum()

features=["title",
    "director",
    "country",
    "rating",
    "listed_in",
    "type"]
df["combined_features"]=df.title+" "+df.director+" "+df.country+" "+df.rating+" "+df.listed_in+" "+df.type
df

df['combined_features'].head(1)

df.duplicated().sum()

df.head(2)

df['title']=df['title'].str.strip()
df['title']=df['title'].str.lower()

df['title']

df['combined_features'].head(2)

cv=CountVectorizer(stop_words='english')
count_matrix=cv.fit_transform(df['combined_features'])

similarity=cosine_similarity(count_matrix)
similarity

def recommend(title):
  print("NETFLIX RECOMENDATION")
  title=title.lower().strip()
  if title not in df['title'].unique():
    return 'Title not in Database'
  else:
    index=df[df['title']==title].index[0]
    similar_movies=list(enumerate(similarity[index]))
    similar_movies=sorted(similar_movies,key=lambda x:x[1],reverse=True)
    similar_movies=similar_movies[1:11]
    print("Recommended Movies: \n")
    rec=[]
    for index, score in similar_movies:
      rec.append({
            "Title": df.iloc[index]["title"],
            "Type": df.iloc[index]["type"],
            "Genre": df.iloc[index]["listed_in"],
            "Rating": df.iloc[index]["rating"],
            "Similarity": round(score, 2)
        })

    return pd.DataFrame(rec)

recommend("ganglands")

# Movies vs TV Shows
import matplotlib.pyplot as plt
df['type'].value_counts().plot(kind='bar')
plt.title=("Movies vs TV Shows")
plt.xlabel("Type")
plt.ylabel("Count")

# Top 10 Genres
top_gen=df['listed_in'].value_counts().head(10)
top_gen.plot(kind='bar')
plt.title=("Top 10 Genres")
plt.xlabel("Genre")
plt.ylabel("Count")

# Content Released Per Year
df['release_year'].value_counts().head(15).plot(kind='pie')
plt.title=("Content Released Per Year")
plt.xlabel("Year")
plt.ylabel("Count")

import pickle

pickle.dump(df, open("movies.pkl", "wb"))

pickle.dump(similarity, open("similarity.pkl", "wb"))

import os

print(os.listdir())

movies = pickle.load(open("movies.pkl", "rb"))

sim=pickle.load(open("similarity.pkl","rb"))

sim.shape

movies.head()

from google.colab import files

files.download("similarity.pkl")







