# -*- coding: utf-8 -*-
"""Netflix_Title_clustering.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yKYze-pZAJ-5z_gp7Wh8gG1D_iOY7mYN
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

df=pd.read_csv("netflix_ml.csv")
df

df.isnull().sum()

df1 = df[
    [
        "type",
        "country",
        "release_year",
        "duration",
        "listed_in"
    ]
]

df1.head()

df1['duration'].head(10)

print(df1["duration"].head())

from sklearn.preprocessing import LabelEncoder
encoder=LabelEncoder()
categorical_columns = [
"type",
"country",
"listed_in"
]
for col in categorical_columns:
  df1[col]=encoder.fit_transform(df1[col])
df1.head()

from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()
scsled_data=scaler.fit_transform(df1)
scsled_data[:2]

from sklearn.cluster import KMeans
wcss=[]
for i in range(1,11):
  kmeans=KMeans(n_clusters=i,random_state=42)
  kmeans.fit(scsled_data)
  wcss.append(kmeans.inertia_)
print(wcss)
plt.plot(range(1,11),wcss)
plt.title("The Elbow Method")
plt.xlabel("Number of Clusters")
plt.ylabel("WCSS")
plt.show()

from sklearn.cluster import KMeans

kmeans=KMeans(n_clusters=4,random_state=42)
kmeans.fit(scsled_data)
clusters=kmeans.predict(scsled_data)

df1['cluster']=clusters
df1["cluster"] = kmeans.labels_

df1.head()

df1['cluster'].value_counts()

from sklearn.decomposition import PCA
pca=PCA(n_components=2)
pca_data = pca.fit_transform(scsled_data)

plt.figure(figsize=(8,6))
plt.scatter(pca_data[:,0],pca_data[:,1],c=clusters,cmap='viridis')
plt.title("Netflix Content Clusters")

plt.xlabel("Principal Component 1")

plt.ylabel("Principal Component 2")

plt.colorbar(label="Cluster")

plt.show()
----------------------------------PCA-----------------------------------

for i in range(4):
    print(f"\n===== Cluster {i} =====")
    print(df1[df1['cluster']==i].head())

k=df1.groupby('cluster').mean()
plt.plot(k.index,k.values)
plt.xticks(k.index)

plt.show()

p=df1.groupby("cluster")["duration"].mean()
plt.plot(p.index,p.values)

import matplotlib.pyplot as plt

cluster_counts = df1["cluster"].value_counts().sort_index()

plt.figure(figsize=(6,4))

plt.bar(cluster_counts.index.astype(str), cluster_counts.values)

plt.title("Number of Titles in Each Cluster")
plt.xlabel("Cluster")
plt.ylabel("Number of Titles")

plt.show()

avg_duration = df1.groupby("cluster")["duration"].mean()

plt.figure(figsize=(6,4))

plt.bar(avg_duration.index.astype(str), avg_duration.values)

plt.title("Average Duration by Cluster")
plt.xlabel("Cluster")
plt.ylabel("Average Duration")

plt.show()

plt.figure(figsize=(8,4))

plt.hist(df1["release_year"], bins=20)

plt.title("Distribution of Release Years")
plt.xlabel("Release Year")
plt.ylabel("Number of Titles")

plt.show()

