# -*- coding: utf-8 -*-
"""Netflix_Trend_Forecasting.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CmF3OMmyg9WijbqjfHxam4kAPhhxsBh6
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
df=pd.read_csv("netflix_ml.csv")
df

df.head()
df['release_year'].value_counts(ascending=False)

df['release_year'].head(1)
df['release_year'].dtypes

yearly_release=df.groupby('release_year').size().reset_index(name='count')
yearly_release=yearly_release.sort_values("release_year")
yearly_release

plt.figure(figsize=(10,5))
plt.plot(yearly_release['release_year'],yearly_release['count'])
plt.xlabel('year')
plt.title("Netflix Content Release Trend")
plt.xlabel("Release Year")
plt.ylabel("Number of Titles")
plt.grid()

yearly_release.head()
yearly_release.tail()

yearly_release.tail(15)

forecast_df=yearly_release[yearly_release['release_year']>=2007].copy()
forecast_df.head()

train=forecast_df[forecast_df['release_year']<=2018]
test=forecast_df[forecast_df['release_year']>2018]
print("train data:",train)
print("test data:",test)

x_train=train[['release_year']]
y_train=train['count']
x_test=test[['release_year']]
y_test=test['count']
print(x_train.shape)
print(x_test.shape)

from sklearn.linear_model import LinearRegression
model=LinearRegression()
model.fit(x_train,y_train)
y_pred=model.predict(x_test)
y_pred

import matplotlib.pyplot as plt

plt.figure(figsize=(8,5))

plt.plot(
    test["release_year"],
    y_test,
    marker="o",
    label="Actual"
)

plt.plot(
    test["release_year"],
    y_pred,
    marker="o",
    label="Predicted"
)

plt.title("Actual vs Predicted Netflix Releases")
plt.xlabel("Release Year")
plt.ylabel("Number of Titles")

plt.legend()
plt.grid()

plt.show()

from sklearn.metrics import mean_absolute_error

mae = mean_absolute_error(y_test, y_pred)

print("MAE:", mae)

from sklearn.metrics import mean_squared_error
import numpy as np

rmse = np.sqrt(mean_squared_error(y_test, y_pred))

print("RMSE:", rmse)

comparison = pd.DataFrame({
    "Year": test["release_year"],
    "Actual": y_test.values,
    "Predicted": y_pred
})

comparison

future_years = pd.DataFrame({
    "release_year": [2022, 2023, 2024, 2025]
})

future_predictions=model.predict(future_years)
future_predictions

future_forecast=pd.DataFrame({
    "release_year":future_years["release_year"],
    "count":future_predictions
})
future_forecast

plt.figure(figsize=(10,5))

plt.plot(
    forecast_df["release_year"],
    forecast_df["count"],
    marker="o",
    label="Historical"
)

plt.plot(
    future_forecast["release_year"],
    future_forecast["count"],
    marker="o",
    linestyle="--",
    label="Forecast"
)

plt.title("Netflix Content Release Trend and Future Forecast")
plt.xlabel("Year")
plt.ylabel("Number of Titles")

plt.legend()
plt.grid()

plt.show()

